version: "3.7"

services:
  db:
    image: postgres:14.1
    env_file:
      - env/.backend.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - env/.backend.env
    ports:
      - "80:8080"
